# Generated by Django 5.1.1 on 2024-10-23 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('error', 'Error'), ('completed', 'Completed')], max_length=20)),
                ('cash_flow_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hub.cashflowmodel')),
            ],
        ),
    ]
